name: Test It

on:
  push:
  pull_request:
  release:
  workflow_dispatch:

jobs:
  test-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [27]
        rebar: [3.24.0]
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Setup Beam
        uses: erlef/setup-beam@v1
        with:
          version-type: strict
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar}}

      - name: Run Tests
        env:
          ERL_FLAGS: "-enable-feature all"
        run: rebar3 test
